{% set name = "praw" %}
{% set version = "7.6.0" %}
{% set sha256 = "3eeebe093f2d905b6c99e18aa8c8f64071b2e7a05e60b618166ee53397cdae72" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - prawcore >=2.1,<3
    - update_checker >=0.18
    - websocket-client >=0.54.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - praw

about:
  home: https://praw.readthedocs.io/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Reddit API Wrapper allows for simple access to Reddit's API
  description: |
    PRAW, an acronym for "Python Reddit API Wrapper", is a python package that
    allows for simple access to Reddit's API. PRAW aims to be easy to use and
    internally follows all of Reddit's API rules. With PRAW there's no need to
    introduce sleep calls in your code. Give your client an appropriate user
    agent and you're set.
  doc_url: https://praw.readthedocs.io/
  dev_url: https://github.com/praw-dev/praw

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - djsutherland
