travis:
  secure:
    BINSTAR_TOKEN: XOSuIuQefR4LHDCPdvLrpr9knu/yS31XSMXD9C4/dPSwrvrpZvzGCx0qVdHFNORLDV4bLx4jKsKcU4JRnFPL52DrhE6xuVG21SDXy/SRytBgokgQ95+IqkUuTA888qTBfDR5eYkVW9buEfSrERKVe0HJlAlMh9u1tbr1T5ER3p/frOyks9fHjSW5IUQLJofc1AFSlKaHh1RnSDIKaKOY8fTVmqwhm2EHEqKgB5j9W0RaWq4kiPxqV/l79BBZYr5Khl5YDZabRYSJGI/zKGg8gTkgKbWL41fRuuFrQaWV4tnPg+Hts4THw0QK2kSrenEyLEHjHGhbwzKyfwz7QSFOsyFwGET9uYj66s6LlhFzv/CtN4WyEHrjGCPK293Qy06tTk13I0A3RMWCRZuVvkY/FE1E2tgHSMAE8glpxg2J7i0iRPT3MhGEWT87CYRS9zFAmU3Fx0bjlApEWCAVKcYykMr7RbGJ3JOp37FbzsAC9sdMu7Hch1xvaW9QsZSvdpNnpuajVUvzV64e8GBZmsIpHZd1DYu+iSmlLE614sAa/P3RCxvZW+l6SibXuli4Yo+daApIFVQNZOkLQpRj/qyA4ywwhh0n5W6qeO9GVTV4HF0hKL0n3XDnT3uzlb0WaIK4Z56p3zA7RjFceob1i0PRjexDxueiKuK3g4BbbGfR9HM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
