travis:
  secure:
    BINSTAR_TOKEN: S6f35PqkOq+Q5U8H1IQQIflhfHkRKvYyKDsTZQ4PQGXvRdeN6bRgJLoGULeoa/7FK50cNIq7HgO7Sktg6/89RhHH6XXOJTejAlxbRfNqWI5V/n/AM40HHMmf2Oiw2D48zyYOavkeDKPMeJbHR/5q3WvlTu+ViHNbVnoAW63OylPinNm6m0/dFSYgR04YQZvBz0FKnhvB2XRFWDjnW2rOcjpo/pEXhvjSX/Lfm9zbl+N/+spvJEAEDWqdFPssRsV4ynwe/yZBi3zgA7tWhKkg6xCcauV/pjuAO57Bphty6JeqNYeGLz3D1/8/x/nLMmBDiJbeBkBY+SLMdJjK6H1dgk5CSQPVPQgaOZS1Cd9oWvmFHQQJuhNsqCgW4OlRqVlqG+SaUepeVKHW+M0cG+JGAxOeJzEc+jMFE7VhLvE0AW/xGEE0qYQiy/54l+/dnHJoM+pd8fP4G7OBv3eJ/UhVIndgawPU4XcKKJRXbHZxdsL3PGjPa904WmpAdf+szx+GuoYucAS1GeQGPveyMRsr/SwPf26xqZpLgXZSGqeYn70jaMkxfGO1wPUKH2s+sKIelCVqxEqYfgMo6gSQA2hFBf1ynB3HbIZYRdmwhfrr8cvpZTUU+3UKuaIx5NTj2CNapPma701/mVg5cZkamwpLbP68X3RtfJG22fsCYCAF9so=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
